Taskana/TaskanaAdapter

- .travis.yml
- ci/commitPoms.sh
See https://github.com/Taskana/taskana/pull/868
Please let me merge this PR since some things have to be done beforehand
> TSK-1050: fixed pushback to github and let the build fail if it wont work

- .travis.yml
- ci/test.sh
- pom.xml
SonarCloud Quality Gate passed:
https://sonarcloud.io/dashboard?branch=ADPT-77&id=gitgoodjhe_TaskanaAdapter
> ADPT-77 Enable SonarCloud for Adapter

- taskana-adapter-camunda-listener-example/src/main/java/pro/taskana/impl/ComplexProcessVariableRetriever.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/mapper/JacksonConfigurator.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/parselistener/TaskanaParseListener.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/parselistener/TaskanaParseListenerProcessEnginePlugin.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/schemacreator/TaskanaOutboxSchemaCreator.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/tasklistener/TaskanaTaskListener.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/util/ReadPropertiesHelper.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/config/OutboxRestServiceConfig.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/model/CamundaTaskEvent.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/resource/CamundaTaskEventListResourceAssembler.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java
- taskana-adapter-camunda-spring-boot-test/src/main/java/acceptance/taskrouting/TestTaskRouterForDomainA.java
- taskana-adapter-camunda-spring-boot-test/src/main/java/acceptance/taskrouting/TestTaskRouterForDomainB.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestCompletedTaskRetrieval.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskClaim.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/impl/ComplexProcessVariableRetriever.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/camunda/outbox/rest/CamundaTaskEvent.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskClaimCanceler.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskCompleter.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskEventCleaner.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskRetriever.java
- taskana-adapter-camunda-wildfly-example/src/main/java/pro/taskana/sample/taskrouting/ExampleTaskRoutingProviderForAdapterTest.java
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskInformationMapper.java
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskanaSystemConnectorImpl.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/TaskanaTaskStarter.java
- taskana-adapter/src/main/java/pro/taskana/adapter/manager/AdapterManager.java
https://sonarcloud.io/dashboard?branch=ADPT-78&id=gitgoodjhe_TaskanaAdapter
Bugs 4 -> 0
Vulnerabilities 2-> 0
Code Smells 104 -> 64
NOTE: 
-new duplicated code because of preexisting duplicated classes!
-test coverage wrong, because it's still about the "old code", where coverage doesn't work properly for now
> ADPT-78 Fix Vulnerabilities, Bugs, CodeSmells

- .gitignore
- pom.xml
- sonar-project.properties
- taskana-adapter-camunda-listener-example/pom.xml
- taskana-adapter-camunda-spring-boot-sample/pom.xml
- taskana-adapter-camunda-spring-boot-test/pom.xml
- taskana-adapter-camunda-system-connector/pom.xml
- taskana-adapter-camunda-wildfly-example/pom.xml
adjusted poms for SonarCloud and aggregated jacoco report
added ingnores for macOS files
> Adpt 81: adjusted pom's for SonarCloud and aggregated jacoco report

- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/dto/ReferencedTask.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/tasklistener/TaskanaTaskListener.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestCancelledTaskRetrieval.java
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskanaSystemConnectorImpl.java
- taskana-adapter/src/main/java/pro/taskana/adapter/systemconnector/api/ReferencedTask.java
SonarCloud is green: https://sonarcloud.io/dashboard?branch=TSK-1166&id=BerndBreier_TaskanaAdapter
> TSK-1166 exploit states TERMINATED and CANCELLED from adapter

- taskana-adapter-camunda-spring-boot-sample/src/main/resources/application.properties
- taskana-adapter-camunda-spring-boot-test/src/main/resources/application.properties
- taskana-adapter-camunda-spring-boot-test/src/main/resources/application.properties.h2
- taskana-adapter-camunda-spring-boot-test/src/main/resources/application.properties.postgres
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/AbsIntegrationTest.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskClaimCanceler.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskClaimer.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskCompleter.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskEventCleaner.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskRetriever.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/HttpHeaderProvider.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/config/CamundaSystemConnectorConfiguration.java
- taskana-adapter-camunda-system-connector/src/main/resources/application.properties
- taskana-adapter-camunda-system-connector/src/test/java/pro/taskana/camunda/camundasystemconnector/configuration/CamundaConnectorTestConfiguration.java
- taskana-adapter-camunda-wildfly-example/src/main/resources/application.properties
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskInformationMapper.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/ReferencedTaskClaimCanceler.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/ReferencedTaskClaimer.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/ReferencedTaskCompleter.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/TaskanaTaskStarter.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/TaskanaTaskTerminator.java
SonarCloud is green: https://sonarcloud.io/dashboard?branch=TSK-1172&id=BerndBreier_TaskanaAdapter
> TSK-1172 add Basic authentication headers to rest clients

- taskana-adapter-camunda-listener/src/main/resources/taskana-outbox.properties
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/TaskanaConfigurationProperties.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java
- taskana-adapter-camunda-outbox-rest/src/main/resources/taskana-outbox.properties
- taskana-adapter-camunda-spring-boot-test/src/main/resources/taskana-outbox.properties
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskRetriever.java
Sonarcloud is green: https://sonarcloud.io/dashboard?branch=TSK-1175&id=BerndBreier_TaskanaAdapter
> TSK-1175 limit number of events returned by outbox Rest Api

- .github/auto-comment.yml
I updated the PR with the changes we requested in community of practices.
> ADPT-97: Enhance auto-comment bot with checklist from team agreements

- pom.xml
- taskana-adapter-camunda-listener-example/pom.xml
- taskana-adapter-camunda-spring-boot-sample/src/main/resources/application.properties
- taskana-adapter-camunda-spring-boot-sample/src/main/resources/taskana.properties
- taskana-adapter-camunda-spring-boot-test/src/main/resources/application.properties
- taskana-adapter-camunda-spring-boot-test/src/main/resources/taskana.properties
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/AbsIntegrationTest.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestCancelledTaskRetrieval.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestCompletedTaskRetrieval.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskAcquisition.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskClaim.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/security/JaasExtension.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/security/WithAccessId.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/security/WithAccessIds.java
- taskana-adapter-camunda-wildfly-example/src/main/resources/application.properties
- taskana-adapter-camunda-wildfly-example/src/main/resources/taskana.properties
- taskana-adapter-taskana-connector/pom.xml
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/config/TaskanaSystemConnectorConfiguration.java
- taskana-adapter/pom.xml
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/ReferencedTaskClaimCanceler.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/ReferencedTaskClaimer.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/ReferencedTaskCompleter.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/TaskanaTaskStarter.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/TaskanaTaskTerminator.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/UserContext.java
Sonarcloud: https://sonarcloud.io/dashboard?branch=ADPT-99&id=gitgoodjhe_TaskanaAdapter
updated doc (will be updated more when I'm back from vacation): https://taskana.atlassian.net/wiki/spaces/TAS/pages/996966415/Adapter+Properties
> ADPT-99: Run adapter scheduled task with JAAS subject

- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestCompletedTaskRetrieval.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskAcquisition.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaSystemConnectorImpl.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskCompleter.java
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskInformationMapper.java
Sonarcloud: https://sonarcloud.io/dashboard?branch=ADPT-104&id=gitgoodjhe_TaskanaAdapter
> ADPT-104: Change Process variable mapping to customAttributesMap

- taskana-adapter-camunda-listener/src/main/resources/sql/taskana-outbox-schema.sql
- taskana-adapter-camunda-spring-boot-test/src/main/resources/processes/simple_user_task_process_with_big_complex_variables.bpmn
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestCompletedTaskRetrieval.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskAcquisition.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/impl/ComplexProcessVariableSetter.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/impl/ProcessVariableTestObject.java
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskInformationMapper.java
Sonarcloud: https://sonarcloud.io/dashboard?branch=ADPT-94&id=gitgoodjhe_TaskanaAdapter
> ADPT-94: Enable large payloads for process variables

- .travis.yml
- camunda-outbox-example-boot/pom.xml
- ci/test.sh
- pom.xml
> ADPT-111: updated adapter to jdk11

- .travis.yml
> ADPT-111: fixed build by properly importing gpg key

- camunda-outbox-example-boot/pom.xml
- pom.xml
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/parselistener/TaskanaParseListenerProcessEnginePlugin.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/schemacreator/TaskanaOutboxSchemaCreator.java
> ADPT-114: Update to Spring Boot 2.3.5

- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/config/OutboxRestServiceConfig.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/controller/CamundaTaskEventsController.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/exception/JsonParseExceptionMapper.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/exception/MismatchedInputExceptionMapper.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java
> ADPT-113: Adjust setRemainingRetries for Jersey

- .travis.yml
> ADPT-111: finally fixed build by properly setting up gpg

- .gitignore
- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- .travis.yml
- ci/change_version.sh
- ci/test.sh
- mvnw
- mvnw.cmd
> ADPT-115: added maven-wrapper

- pom.xml
> ADPT-116: IntelliJ not detecing proper language level (11)

- taskana-adapter-camunda-spring-boot-sample/src/main/resources/application.properties
> Fix typos in comment

- pom.xml
- taskana-adapter-camunda-spring-boot-test/pom.xml
- taskana-adapter-camunda-system-connector/pom.xml
> ADPT-119: Bump Spring Boot Version to 2.4.0

- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/AbsIntegrationTest.java
> ADPT-121: Add classification service level to fix tests

- README.md
> ADPT-120: updated travis-ci badge to link to new repo

- camunda-outbox-example-boot/src/main/java/pro/taskana/camunda/spring/boot/CamundaSpringBootExample.java
- qa/intellij/taskana_formatter_intellij.xml
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/parselistener/TaskanaParseListenerProcessEnginePlugin.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/schemacreator/TaskanaOutboxSchemaCreator.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/controller/Mapping.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/exception/CamundaTaskEventNotFoundException.java
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/model/CamundaTaskEvent.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaUtilRequester.java
- taskana-adapter-camunda-system-connector/src/test/java/pro/taskana/camunda/camundasystemconnector/acceptance/RetrieveCamundaTaskAccTest.java
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskanaSystemConnectorImpl.java
- taskana-adapter/src/main/java/pro/taskana/adapter/impl/UserContext.java
- taskana-adapter/src/main/java/pro/taskana/adapter/systemconnector/api/SystemConnector.java
and reformatted a lot of files
---
> ADPT-122: added custom taskana formatter changes to formatter

- .github/workflows/continuous-integration.yml
> ADPT-124: fixed tag regex.

- .github/workflows/continuous-integration.yml
> ADPT-124: enabled release for Taskana/TaskanaAdapter

- .github/workflows/continuous-integration.yml
> ADPT-124: fixed schedule time for workflow

- .github/workflows/continuous-integration.yml
> ADPT-129: now using PAT of admin for release job

- taskana-adapter-camunda-listener/pom.xml
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/CamundaListenerConfiguration.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/exceptions/SystemException.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/parselistener/TaskanaParseListenerProcessEnginePlugin.java
> ADPT-125: Remove taskana-common dependency from listener module

- taskana-adapter-camunda-spring-boot-test/src/main/resources/application.properties
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestDisabledTaskClaim.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskClaimer.java
> ADPT-128: Make claiming of camunda tasks configurable

- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/CamundaListenerConfiguration.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/tasklistener/TaskanaTaskListener.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskClaimer.java
> ADPT-118: Rethrow/Remove exceptions in the TaskListener

- qa/checkstyle/checkstyle.xml
> ADPT-130: Update checkstyle configuration file

- .github/workflows/continuous-integration.yml
> ADPT-132: updated setup-java action to v2

- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskanaSystemConnectorImpl.java
> ADPT-134: fix compile issues introduced by TASKANA API changes

- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/tasklistener/TaskanaTaskListener.java
- taskana-adapter-camunda-spring-boot-test/src/main/resources/processes/simple_user_task_process_with_empty_extension_property.bpmn
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskAcquisition.java
> ADPT-135: Exception for empty Self-Closing-Tags in BPM-XML

- taskana-adapter-camunda-spring-boot-test/src/main/resources/processes/simple_user_task_with_assignee_process.bpmn
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestDisabledTaskClaim.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskClaimCanceler.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskClaimer.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskEventErrorHandler.java
> ADPT-136: Make synchronization of CancelClaim configurable

- pom.xml
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskAcquisition.java
> ADPT-139: updated google-java-format to 1.13

- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaSystemConnectorImpl.java
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskanaSystemConnectorImpl.java
- taskana-adapter/src/main/java/pro/taskana/adapter/manager/AdapterManager.java
> ADPT-141: Improved initialization logging for connectors.

- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestDisabledTaskClaim.java
> ADPT-138: Fix TestDisabledTaskClaim Test

- .github/workflows/continuous-integration.yml
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskInformationMapper.java
> ADPT-145: Adjust ObjectReference usage

- camunda-outbox-example-boot/pom.xml
- pom.xml
- taskana-adapter-camunda-spring-boot-test/pom.xml
- taskana-adapter-camunda-spring-boot-test/src/main/resources/application.properties
- taskana-adapter-camunda-spring-boot-test/src/main/resources/application.properties.h2
- taskana-adapter-camunda-spring-boot-test/src/main/resources/application.properties.postgres
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/CamundaProcessengineRequester.java
- taskana-adapter-camunda-spring-boot-test/src/test/resources/logback-test.xml
> ADPT-144: Update Camunda to 7.16

- .github/workflows/continuous-integration.yml
> ADPT-153: replaced workflow-run-cleanup-action with new concurrency cmd

- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/tasklistener/TaskanaTaskListener.java
- taskana-adapter-camunda-spring-boot-test/src/main/resources/processes/simple_user_task_process_with_different_domains.bpmn
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskAcquisition.java
docs:
* https://taskana.atlassian.net/wiki/spaces/TAS/pages/881164289/Camunda+BPM+Connector
sonar:
* https://sonarcloud.io/summary/new_code?id=ensarevlideveloper_TaskanaAdapter&branch=ADPT-148
---
> ADPT-148: Allow overwriting of domain if defined in task

- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/tasklistener/TaskanaTaskListener.java
- taskana-adapter-camunda-spring-boot-test/src/main/resources/processes/simple_user_task_process_with_multiple_tasks_and_complex_variables.bpmn
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskAcquisition.java
> ADPT-150: Different taskana-attributes for different User-Tasks

- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/dto/ReferencedTask.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/tasklistener/TaskanaTaskListener.java
- taskana-adapter-camunda-listener/src/test/java/pro/taskana/adapter/camunda/dto/ReferencedTaskTest.java
- taskana-adapter-camunda-spring-boot-test/src/main/resources/processes/simple_user_task_process_with_plannedDate.bpmn
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskAcquisition.java
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskInformationMapper.java
- taskana-adapter/src/main/java/pro/taskana/adapter/systemconnector/api/ReferencedTask.java
> ADPT-149: FollowUp Date is now assigned by Camunda Listener

- pom.xml
- taskana-adapter-camunda-spring-boot-example/pom.xml
- taskana-adapter-camunda-spring-boot-test/pom.xml
- taskana-adapter-camunda-wildfly-example/pom.xml
- taskana-adapter-taskana-connector/pom.xml
> ADPT-158: replace Db2 JDBC driver with official one (from maven central)

- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/dto/ReferencedTask.java
- taskana-adapter-camunda-listener/src/main/java/pro/taskana/adapter/camunda/tasklistener/TaskanaTaskListener.java
- taskana-adapter-camunda-listener/src/test/java/pro/taskana/adapter/camunda/dto/ReferencedTaskTest.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestTaskAcquisition.java
- taskana-adapter-camunda-system-connector/src/test/java/pro/taskana/camunda/camundasystemconnector/acceptance/RetrieveCamundaTaskAccTest.java
- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/api/impl/TaskInformationMapper.java
- taskana-adapter/src/main/java/pro/taskana/adapter/systemconnector/api/ReferencedTask.java
- taskana-adapter/src/test/java/pro/taskana/adapter/systemconnector/api/ReferencedTaskTest.java
During the Introduction we also introduced a new method which gets Variables from delegateTasks generically.
SONAR:
[* link](https://sonarcloud.io/summary/new_code?id=ensarevlideveloper_TaskanaAdapter&branch=ADPT-162)
---
> ADPT-162: Introduction of CustomInt-Fields

- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java
- taskana-adapter-camunda-spring-boot-test/src/main/java/pro/taskana/adapter/test/TaskanaAdapterTestApplication.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/CamundaTaskEventErrorHandlerTest.java
- taskana-adapter-camunda-spring-boot-test/src/test/java/pro/taskana/adapter/integration/TestFailedTaskCreation.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskEventErrorHandler.java
> ADPT-166: Create Exception-Tree for ErrorLog and Tests

- taskana-adapter-camunda-listener/src/test/java/pro/taskana/adapter/camunda/dto/ReferencedTaskTest.java
- taskana-adapter-camunda-system-connector/src/main/java/pro/taskana/adapter/systemconnector/camunda/api/impl/CamundaTaskRetriever.java
- taskana-adapter/src/test/java/pro/taskana/adapter/systemconnector/api/ReferencedTaskTest.java
[Sonar](https://sonarcloud.io/summary/new_code?id=ensarevlideveloper_TaskanaAdapter&branch=ADPT-169)
> ADPT-169: Fixed bugs

- pom.xml
> TSK-2009: changes to immutable TaskanaConfiguration

- pom.xml
- taskana-adapter-camunda-listener-example/pom.xml
- taskana-adapter-camunda-wildfly-example/pom.xml
no code changes, no sonar cloud
---
> Closes #561 : Integrate TASKANA 6.1.0, Spring 5.3.26 and Spring Boot 2.7.10

- taskana-adapter-taskana-connector/src/main/java/pro/taskana/adapter/taskanaconnector/config/TaskanaSystemConnectorConfiguration.java
> Closes #574 - enable custom TaskanaConfiguration Bean

- pom.xml
> Closes #581 Integrate TASKANA 6.2.0

- pom.xml
Bumps `version.camunda.spin` from 1.18.0 to 1.19.1.
Updates `camunda-spin-dataformat-all` from 1.18.0 to 1.19.1
- [Release notes](https://github.com/camunda/camunda-spin/releases)
- [Commits](https://github.com/camunda/camunda-spin/compare/1.18.0...1.19.1)
Updates `camunda-spin-bom` from 1.18.0 to 1.19.1
- [Release notes](https://github.com/camunda/camunda-spin/releases)
- [Commits](https://github.com/camunda/camunda-spin/compare/1.18.0...1.19.1)
Updates `camunda-spin-core` from 1.18.0 to 1.19.1
- [Release notes](https://github.com/camunda/camunda-spin/releases)
- [Commits](https://github.com/camunda/camunda-spin/compare/1.18.0...1.19.1)
Updates `camunda-spin-dataformat-json-jackson` from 1.18.0 to 1.19.1
- [Release notes](https://github.com/camunda/camunda-spin/releases)
- …
> Rerunning Bump version.camunda.spin from 1.18.0 to 1.19.1

- .github/workflows/continuous-integration.yml
- camunda-outbox-example-boot/pom.xml
- ci/taskana-adapter-sonar-test-coverage/pom.xml
- pom.xml
- taskana-adapter-camunda-listener-example/pom.xml
- taskana-adapter-camunda-listener/pom.xml
- taskana-adapter-camunda-outbox-rest-spring-boot-starter/pom.xml
- taskana-adapter-camunda-outbox-rest/pom.xml
- taskana-adapter-camunda-spring-boot-example/pom.xml
- taskana-adapter-camunda-spring-boot-test/pom.xml
- taskana-adapter-camunda-system-connector/pom.xml
- taskana-adapter-camunda-wildfly-example/pom.xml
- taskana-adapter-taskana-connector/pom.xml
- taskana-adapter/pom.xml
https://sonarcloud.io/summary/new_code?id=arolfes_TaskanaAdapter&branch=java_17
---
> Closes #552 Java 17 migration

- pom.xml
- taskana-adapter-camunda-listener-example/pom.xml
- taskana-adapter-camunda-listener/pom.xml
- taskana-adapter-camunda-outbox-rest/pom.xml
- taskana-adapter-camunda-outbox-rest/src/main/java/pro/taskana/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java
-  taskana-adapter-camunda-outbox-rest 
-  taskana-adapter-camunda-listener
are now compatible with java 8
---
> Closes #656 - make relevant modules java 8 compatible

- docker-databases/prepare_db.bat
- docker-databases/prepare_db.sh
- taskana-adapter-camunda-wildfly-example/src/test/java/pro/taskana/adapter/example/wildfly/AbstractAccTest.java
> Closes #710: Use "docker compose" instead of "docker-compose"

- pom.xml
- taskana-adapter-camunda-wildfly-example/src/test/resources/module.xml
> Closes #708 - update to SpringBoot 3.3.2

- .github/workflows/continuous-integration.yml
- ci/mvnsettings.xml
> Closes #742 Sonatype Config

- pom.xml
> Closes #726 Integrate TASKANA 8.2.0
